CONFIG_GPIO=y

#printk e printf completa
CONFIG_SERIAL=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_NEWLIB_LIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

CONFIG_ADC=y

#logging
CONFIG_LOG=y               
# Mostra mensagens até LOG_INF (níveis: 0–4) 
CONFIG_LOG_DEFAULT_LEVEL=3
# logging deferred
CONFIG_LOG_MODE_DEFERRED=y
# Habilitando timestamp no formato hh:mm:ss:mmm,uuu
CONFIG_LOG_TIMESTAMP_64BIT=y
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=y
